// Generated by CoffeeScript 1.4.0
(function() {
  var App, _ref;

  if ((_ref = window.birdseye) == null) {
    window.birdseye = {};
  }

  App = (function() {

    function App() {}

    App.prototype.organisations = ko.observableArray([]);

    App.prototype.selectedOrganisation = ko.observable();

    App.prototype.user = ko.observable(new birdseye.User());

    return App;

  })();

  window.birdseye.App = App;

}).call(this);
