// Generated by CoffeeScript 1.6.1
(function() {
  var App, _ref,
    _this = this;

  if ((_ref = window.birdseye) == null) {
    window.birdseye = {};
  }

  App = (function() {

    function App() {
      var _this = this;
      this._error = function(m) {
        return App.prototype._error.apply(_this, arguments);
      };
      this._fetchOrganisations = function() {
        return App.prototype._fetchOrganisations.apply(_this, arguments);
      };
      this.organisations = ko.observableArray([]);
      this.selectedOrganisation = ko.observable();
      this.user = ko.observable(new birdseye.User());
      this.errors = ko.observable(new birdseye.Errors());
      this.memberFilter = ko.observable("");
      this.adminsOnly = ko.observable(false);
      this.nonOrgOnly = ko.observable(false);
      this.user().organisationIds.subscribe(this._fetchOrganisations);
      this.selectedOrganisation.subscribe(function(org) {
        if (org != null) {
          return org.loadAll();
        }
      });
    }

    App.prototype._fetchOrganisations = function() {
      var _this = this;
      console.log("Fetching orgs");
      this.organisations([]);
      return this.user().organisationIds().forEach(function(id) {
        console.log("Fetching org with id: " + id);
        return Trello.organizations.get(id, {}, function(data) {
          var org;
          org = new birdseye.Organisation(id, data.displayName, _this.errors(), _this.memberFilter, _this.adminsOnly, _this.nonOrgOnly);
          _this.organisations.push(org);
          if (_this.organisations.length === 1) {
            return _this.selectedOrganisation(org);
          }
        }, _this._error);
      });
    };

    App.prototype._error = function(m) {
      this.errors().add(m);
      return console.log("App: Error: " + m);
    };

    return App;

  })();

  window.birdseye.App = App;

}).call(this);
