// Generated by CoffeeScript 1.4.0
(function() {
  var Board, _ref;

  if ((_ref = window.birdseye) == null) {
    window.birdseye = {};
  }

  Board = (function() {

    function Board(id, name, memberships) {
      this.id = id;
      this.name = ko.observable(name);
      this.memberships = ko.observableArray(memberships);
    }

    return Board;

  })();

  window.birdseye.Board = Board;

}).call(this);
