// Generated by CoffeeScript 1.4.0
(function() {
  var Board, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  if ((_ref = window.birdseye) == null) {
    window.birdseye = {};
  }

  Board = (function() {

    function Board(id, name, memberships, memberFilter) {
      var _this = this;
      this.id = id;
      this._filterBy = __bind(this._filterBy, this);

      this.name = ko.observable(name);
      this.memberships = ko.computed(function() {
        return _this._filterBy(memberFilter, memberships);
      });
    }

    Board.prototype._filterBy = function(memberFilter, memberships) {
      var _this = this;
      if (memberFilter() != null) {
        return memberships.filter(function(m) {
          return m.member().matches(memberFilter());
        });
      } else {
        return memberships;
      }
    };

    return Board;

  })();

  window.birdseye.Board = Board;

}).call(this);
