// Generated by CoffeeScript 1.4.0
(function() {
  var Errors, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  if ((_ref = window.birdseye) == null) {
    window.birdseye = {};
  }

  Errors = (function() {

    function Errors() {
      this.add = __bind(this.add, this);

    }

    Errors.prototype.seen = ko.observableArray();

    Errors.prototype.add = function(m) {
      return seen.push(m);
    };

    return Errors;

  })();

  window.birdseye.Errors = Errors;

}).call(this);
