// Generated by CoffeeScript 1.6.1
(function() {
  var Errors, _ref,
    _this = this;

  if ((_ref = window.birdseye) == null) {
    window.birdseye = {};
  }

  Errors = (function() {

    function Errors() {
      var _this = this;
      this.add = function(m) {
        return Errors.prototype.add.apply(_this, arguments);
      };
    }

    Errors.prototype.seen = ko.observableArray();

    Errors.prototype.add = function(m) {
      return seen.push(m);
    };

    return Errors;

  })();

  window.birdseye.Errors = Errors;

}).call(this);
