// Generated by CoffeeScript 1.4.0
(function() {
  var Member, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  if ((_ref = window.birdseye) == null) {
    window.birdseye = {};
  }

  Member = (function() {

    function Member(id, fullName, username) {
      this.id = id;
      this.matches = __bind(this.matches, this);

      this.fullName = ko.observable(fullName);
      this.username = ko.observable(username);
    }

    Member.prototype.matches = function(filter) {
      var f;
      if (filter != null) {
        f = filter.toLowerCase();
        return this.fullName().toLowerCase().indexOf(f) >= 0 || this.username().indexOf(f) >= 0;
      } else {
        return true;
      }
    };

    return Member;

  })();

  window.birdseye.Member = Member;

}).call(this);
