// Generated by CoffeeScript 1.4.0
(function() {
  var Membership, _ref;

  if ((_ref = window.birdseye) == null) {
    window.birdseye = {};
  }

  Membership = (function() {

    function Membership(idMember, type, isMember) {
      this.idMember = ko.observable(idMember);
      this.type = ko.observable(type);
      this.isMember = ko.observable(isMember);
    }

    return Membership;

  })();

  window.birdseye.Membership = Membership;

}).call(this);
