// Generated by CoffeeScript 1.4.0
(function() {
  var Membership, _ref;

  if ((_ref = window.birdseye) == null) {
    window.birdseye = {};
  }

  Membership = (function() {

    function Membership(member, type, orgMember) {
      this.member = ko.observable(member);
      this.type = ko.observable(type);
      this.orgMember = ko.observable(orgMember);
    }

    return Membership;

  })();

  window.birdseye.Membership = Membership;

}).call(this);
