// Generated by CoffeeScript 1.4.0
(function() {
  var User, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  if ((_ref = window.birdseye) == null) {
    window.birdseye = {};
  }

  User = (function() {

    User.prototype.status = ko.observable("signed-out");

    User.prototype.name = ko.observable();

    function User() {
      this._updateName = __bind(this._updateName, this);

      this._error = __bind(this._error, this);

      this._signIn = __bind(this._signIn, this);

      this.signOut = __bind(this.signOut, this);

      this.freshSignIn = __bind(this.freshSignIn, this);

      var _this = this;
      this.signedIn = ko.computed(function() {
        return _this.status() === "signed-in";
      });
    }

    User.prototype.freshSignIn = function() {
      this.signOut();
      return this._signIn();
    };

    User.prototype.signOut = function() {
      Trello.deauthorize();
      this.status("signed-out");
      return this.name(null);
    };

    User.prototype._signIn = function() {
      var _this = this;
      this.status("signing-in");
      return Trello.authorize({
        type: "popup",
        name: "Birds eye",
        success: function() {
          _this.status("signed-in");
          return _this._updateName();
        },
        error: this._error
      });
    };

    User.prototype._error = function(m) {
      this.signOut();
      return console.log("Error: " + m);
    };

    User.prototype._updateName = function() {
      var _this = this;
      return Trello.members.get("me", {}, function(user) {
        return _this.name(user.fullName);
      }, this._error);
    };

    return User;

  })();

  window.birdseye.User = User;

}).call(this);
